# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_service.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'ai_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61i_service.proto\x12\tmcf.ai.v1\"\x84\x02\n\x0cMediaRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x30\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x1e.mcf.ai.v1.MediaRequest.ConfigH\x00\x12\x15\n\x0b\x61udio_chunk\x18\x03 \x01(\x0cH\x00\x12\x17\n\x0fsequence_number\x18\x04 \x01(\x03\x12\x0e\n\x06is_eos\x18\x05 \x01(\x08\x1a\x63\n\x06\x43onfig\x12\x17\n\x0fsource_language\x18\x01 \x01(\t\x12\x17\n\x0ftarget_language\x18\x02 \x01(\t\x12\x12\n\nenable_tts\x18\x03 \x01(\x08\x12\x13\n\x0bsample_rate\x18\x04 \x01(\x05\x42\t\n\x07payload\"\x80\x01\n\rMediaResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x17\n\x0frecognized_text\x18\x02 \x01(\t\x12\x17\n\x0ftranslated_text\x18\x03 \x01(\t\x12\x10\n\x08is_final\x18\x04 \x01(\x08\x12\x17\n\x0ftts_audio_chunk\x18\x05 \x01(\x0c\x32\x61\n\x12TranslationService\x12K\n\x12ProcessMediaStream\x12\x17.mcf.ai.v1.MediaRequest\x1a\x18.mcf.ai.v1.MediaResponse(\x01\x30\x01\x42 Z\x1emcf/services/logic/internal/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\036mcf/services/logic/internal/pb'
  _globals['_MEDIAREQUEST']._serialized_start=32
  _globals['_MEDIAREQUEST']._serialized_end=292
  _globals['_MEDIAREQUEST_CONFIG']._serialized_start=182
  _globals['_MEDIAREQUEST_CONFIG']._serialized_end=281
  _globals['_MEDIARESPONSE']._serialized_start=295
  _globals['_MEDIARESPONSE']._serialized_end=423
  _globals['_TRANSLATIONSERVICE']._serialized_start=425
  _globals['_TRANSLATIONSERVICE']._serialized_end=522
# @@protoc_insertion_point(module_scope)
