# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ai_service_pb2 as ai__service__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TranslationServiceStub:
    """---------------------------------------------------------
    SERVICE DEFINITION
    ---------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessMediaStream = channel.stream_stream(
                '/mcf.ai.v1.TranslationService/ProcessMediaStream',
                request_serializer=ai__service__pb2.MediaRequest.SerializeToString,
                response_deserializer=ai__service__pb2.MediaResponse.FromString,
                _registered_method=True)


class TranslationServiceServicer:
    """---------------------------------------------------------
    SERVICE DEFINITION
    ---------------------------------------------------------
    """

    def ProcessMediaStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranslationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessMediaStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ProcessMediaStream,
                    request_deserializer=ai__service__pb2.MediaRequest.FromString,
                    response_serializer=ai__service__pb2.MediaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mcf.ai.v1.TranslationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mcf.ai.v1.TranslationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TranslationService:
    """---------------------------------------------------------
    SERVICE DEFINITION
    ---------------------------------------------------------
    """

    @staticmethod
    def ProcessMediaStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/mcf.ai.v1.TranslationService/ProcessMediaStream',
            ai__service__pb2.MediaRequest.SerializeToString,
            ai__service__pb2.MediaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
