// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: ai_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ---------------------------------------------------------
// REQUEST DEFINITION (Go -> Python)
// ---------------------------------------------------------
type MediaRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// using 'oneof' to classify: one request can only be either config or media chunk.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*MediaRequest_Config_
	//	*MediaRequest_AudioChunk
	Payload        isMediaRequest_Payload `protobuf_oneof:"payload"`
	SequenceNumber int64                  `protobuf:"varint,4,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"` // to maintain the order of requests
	IsEos          bool                   `protobuf:"varint,5,opt,name=is_eos,json=isEos,proto3" json:"is_eos,omitempty"`                            // end of stream indicator
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MediaRequest) Reset() {
	*x = MediaRequest{}
	mi := &file_ai_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaRequest) ProtoMessage() {}

func (x *MediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaRequest.ProtoReflect.Descriptor instead.
func (*MediaRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{0}
}

func (x *MediaRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MediaRequest) GetPayload() isMediaRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MediaRequest) GetConfig() *MediaRequest_Config {
	if x != nil {
		if x, ok := x.Payload.(*MediaRequest_Config_); ok {
			return x.Config
		}
	}
	return nil
}

func (x *MediaRequest) GetAudioChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*MediaRequest_AudioChunk); ok {
			return x.AudioChunk
		}
	}
	return nil
}

func (x *MediaRequest) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *MediaRequest) GetIsEos() bool {
	if x != nil {
		return x.IsEos
	}
	return false
}

type isMediaRequest_Payload interface {
	isMediaRequest_Payload()
}

type MediaRequest_Config_ struct {
	Config *MediaRequest_Config `protobuf:"bytes,2,opt,name=config,proto3,oneof"` // setup
}

type MediaRequest_AudioChunk struct {
	AudioChunk []byte `protobuf:"bytes,3,opt,name=audio_chunk,json=audioChunk,proto3,oneof"` // pcm audio data
}

func (*MediaRequest_Config_) isMediaRequest_Payload() {}

func (*MediaRequest_AudioChunk) isMediaRequest_Payload() {}

// ---------------------------------------------------------
// RESPONSE DEFINITION (Python -> Go)
// ---------------------------------------------------------
type MediaResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// text response (serve HTTPGW export subtitles)
	RecognizedText string `protobuf:"bytes,2,opt,name=recognized_text,json=recognizedText,proto3" json:"recognized_text,omitempty"` // ASR
	TranslatedText string `protobuf:"bytes,3,opt,name=translated_text,json=translatedText,proto3" json:"translated_text,omitempty"` // MT
	// flag to indicate if this is the final response for the current session
	IsFinal bool `protobuf:"varint,4,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	// audio data (RTPGW audio response)
	TtsAudioChunk []byte `protobuf:"bytes,5,opt,name=tts_audio_chunk,json=ttsAudioChunk,proto3" json:"tts_audio_chunk,omitempty"` // pcm audio data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaResponse) Reset() {
	*x = MediaResponse{}
	mi := &file_ai_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaResponse) ProtoMessage() {}

func (x *MediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaResponse.ProtoReflect.Descriptor instead.
func (*MediaResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{1}
}

func (x *MediaResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MediaResponse) GetRecognizedText() string {
	if x != nil {
		return x.RecognizedText
	}
	return ""
}

func (x *MediaResponse) GetTranslatedText() string {
	if x != nil {
		return x.TranslatedText
	}
	return ""
}

func (x *MediaResponse) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *MediaResponse) GetTtsAudioChunk() []byte {
	if x != nil {
		return x.TtsAudioChunk
	}
	return nil
}

type VideoConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EffectType      string                 `protobuf:"bytes,1,opt,name=effect_type,json=effectType,proto3" json:"effect_type,omitempty"`
	InferenceWidth  uint32                 `protobuf:"varint,2,opt,name=inference_width,json=inferenceWidth,proto3" json:"inference_width,omitempty"`
	InferenceHeight uint32                 `protobuf:"varint,3,opt,name=inference_height,json=inferenceHeight,proto3" json:"inference_height,omitempty"`
	InferenceFps    uint32                 `protobuf:"varint,4,opt,name=inference_fps,json=inferenceFps,proto3" json:"inference_fps,omitempty"`
	Threshold       float32                `protobuf:"fixed32,5,opt,name=threshold,proto3" json:"threshold,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VideoConfig) Reset() {
	*x = VideoConfig{}
	mi := &file_ai_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoConfig) ProtoMessage() {}

func (x *VideoConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoConfig.ProtoReflect.Descriptor instead.
func (*VideoConfig) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{2}
}

func (x *VideoConfig) GetEffectType() string {
	if x != nil {
		return x.EffectType
	}
	return ""
}

func (x *VideoConfig) GetInferenceWidth() uint32 {
	if x != nil {
		return x.InferenceWidth
	}
	return 0
}

func (x *VideoConfig) GetInferenceHeight() uint32 {
	if x != nil {
		return x.InferenceHeight
	}
	return 0
}

func (x *VideoConfig) GetInferenceFps() uint32 {
	if x != nil {
		return x.InferenceFps
	}
	return 0
}

func (x *VideoConfig) GetThreshold() float32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

type VideoFrame struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FrameId        int64                  `protobuf:"varint,1,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	RtpTimestamp   int64                  `protobuf:"varint,2,opt,name=rtp_timestamp,json=rtpTimestamp,proto3" json:"rtp_timestamp,omitempty"`
	OriginalWidth  int32                  `protobuf:"varint,3,opt,name=original_width,json=originalWidth,proto3" json:"original_width,omitempty"`
	OriginalHeight int32                  `protobuf:"varint,4,opt,name=original_height,json=originalHeight,proto3" json:"original_height,omitempty"`
	Encoding       string                 `protobuf:"bytes,5,opt,name=encoding,proto3" json:"encoding,omitempty"`
	ImageData      []byte                 `protobuf:"bytes,6,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VideoFrame) Reset() {
	*x = VideoFrame{}
	mi := &file_ai_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoFrame) ProtoMessage() {}

func (x *VideoFrame) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoFrame.ProtoReflect.Descriptor instead.
func (*VideoFrame) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{3}
}

func (x *VideoFrame) GetFrameId() int64 {
	if x != nil {
		return x.FrameId
	}
	return 0
}

func (x *VideoFrame) GetRtpTimestamp() int64 {
	if x != nil {
		return x.RtpTimestamp
	}
	return 0
}

func (x *VideoFrame) GetOriginalWidth() int32 {
	if x != nil {
		return x.OriginalWidth
	}
	return 0
}

func (x *VideoFrame) GetOriginalHeight() int32 {
	if x != nil {
		return x.OriginalHeight
	}
	return 0
}

func (x *VideoFrame) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

func (x *VideoFrame) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

type VideoRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	IsEos     bool                   `protobuf:"varint,2,opt,name=is_eos,json=isEos,proto3" json:"is_eos,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*VideoRequest_Config
	//	*VideoRequest_Frame
	Payload isVideoRequest_Payload `protobuf_oneof:"payload"`
	// Added as an optional routing key. Existing clients may leave it empty.
	StreamId      string `protobuf:"bytes,5,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoRequest) Reset() {
	*x = VideoRequest{}
	mi := &file_ai_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoRequest) ProtoMessage() {}

func (x *VideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoRequest.ProtoReflect.Descriptor instead.
func (*VideoRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{4}
}

func (x *VideoRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *VideoRequest) GetIsEos() bool {
	if x != nil {
		return x.IsEos
	}
	return false
}

func (x *VideoRequest) GetPayload() isVideoRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *VideoRequest) GetConfig() *VideoConfig {
	if x != nil {
		if x, ok := x.Payload.(*VideoRequest_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *VideoRequest) GetFrame() *VideoFrame {
	if x != nil {
		if x, ok := x.Payload.(*VideoRequest_Frame); ok {
			return x.Frame
		}
	}
	return nil
}

func (x *VideoRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type isVideoRequest_Payload interface {
	isVideoRequest_Payload()
}

type VideoRequest_Config struct {
	Config *VideoConfig `protobuf:"bytes,3,opt,name=config,proto3,oneof"`
}

type VideoRequest_Frame struct {
	Frame *VideoFrame `protobuf:"bytes,4,opt,name=frame,proto3,oneof"`
}

func (*VideoRequest_Config) isVideoRequest_Payload() {}

func (*VideoRequest_Frame) isVideoRequest_Payload() {}

type VideoMask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameId       int64                  `protobuf:"varint,1,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	RtpTimestamp  int64                  `protobuf:"varint,2,opt,name=rtp_timestamp,json=rtpTimestamp,proto3" json:"rtp_timestamp,omitempty"`
	MaskWidth     int32                  `protobuf:"varint,3,opt,name=mask_width,json=maskWidth,proto3" json:"mask_width,omitempty"`
	MaskHeight    int32                  `protobuf:"varint,4,opt,name=mask_height,json=maskHeight,proto3" json:"mask_height,omitempty"`
	RleCounts     []uint32               `protobuf:"varint,5,rep,packed,name=rle_counts,json=rleCounts,proto3" json:"rle_counts,omitempty"`
	LatencyMs     float32                `protobuf:"fixed32,6,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoMask) Reset() {
	*x = VideoMask{}
	mi := &file_ai_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoMask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoMask) ProtoMessage() {}

func (x *VideoMask) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoMask.ProtoReflect.Descriptor instead.
func (*VideoMask) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{5}
}

func (x *VideoMask) GetFrameId() int64 {
	if x != nil {
		return x.FrameId
	}
	return 0
}

func (x *VideoMask) GetRtpTimestamp() int64 {
	if x != nil {
		return x.RtpTimestamp
	}
	return 0
}

func (x *VideoMask) GetMaskWidth() int32 {
	if x != nil {
		return x.MaskWidth
	}
	return 0
}

func (x *VideoMask) GetMaskHeight() int32 {
	if x != nil {
		return x.MaskHeight
	}
	return 0
}

func (x *VideoMask) GetRleCounts() []uint32 {
	if x != nil {
		return x.RleCounts
	}
	return nil
}

func (x *VideoMask) GetLatencyMs() float32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *VideoMask) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VideoMask) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type VideoResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Mask      *VideoMask             `protobuf:"bytes,2,opt,name=mask,proto3" json:"mask,omitempty"`
	IsFinal   bool                   `protobuf:"varint,3,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	// Echoed by the AI Engine so one session can contain multiple video streams.
	StreamId      string `protobuf:"bytes,4,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoResponse) Reset() {
	*x = VideoResponse{}
	mi := &file_ai_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoResponse) ProtoMessage() {}

func (x *VideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoResponse.ProtoReflect.Descriptor instead.
func (*VideoResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{6}
}

func (x *VideoResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *VideoResponse) GetMask() *VideoMask {
	if x != nil {
		return x.Mask
	}
	return nil
}

func (x *VideoResponse) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *VideoResponse) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type MediaRequest_Config struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceLanguage string                 `protobuf:"bytes,1,opt,name=source_language,json=sourceLanguage,proto3" json:"source_language,omitempty"`
	TargetLanguage string                 `protobuf:"bytes,2,opt,name=target_language,json=targetLanguage,proto3" json:"target_language,omitempty"`
	EnableTts      bool                   `protobuf:"varint,3,opt,name=enable_tts,json=enableTts,proto3" json:"enable_tts,omitempty"`
	SampleRate     int32                  `protobuf:"varint,4,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MediaRequest_Config) Reset() {
	*x = MediaRequest_Config{}
	mi := &file_ai_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaRequest_Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaRequest_Config) ProtoMessage() {}

func (x *MediaRequest_Config) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaRequest_Config.ProtoReflect.Descriptor instead.
func (*MediaRequest_Config) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MediaRequest_Config) GetSourceLanguage() string {
	if x != nil {
		return x.SourceLanguage
	}
	return ""
}

func (x *MediaRequest_Config) GetTargetLanguage() string {
	if x != nil {
		return x.TargetLanguage
	}
	return ""
}

func (x *MediaRequest_Config) GetEnableTts() bool {
	if x != nil {
		return x.EnableTts
	}
	return false
}

func (x *MediaRequest_Config) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

var File_ai_service_proto protoreflect.FileDescriptor

const file_ai_service_proto_rawDesc = "" +
	"\n" +
	"\x10ai_service.proto\x12\tmcf.ai.v1\"\xf2\x02\n" +
	"\fMediaRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x128\n" +
	"\x06config\x18\x02 \x01(\v2\x1e.mcf.ai.v1.MediaRequest.ConfigH\x00R\x06config\x12!\n" +
	"\vaudio_chunk\x18\x03 \x01(\fH\x00R\n" +
	"audioChunk\x12'\n" +
	"\x0fsequence_number\x18\x04 \x01(\x03R\x0esequenceNumber\x12\x15\n" +
	"\x06is_eos\x18\x05 \x01(\bR\x05isEos\x1a\x9a\x01\n" +
	"\x06Config\x12'\n" +
	"\x0fsource_language\x18\x01 \x01(\tR\x0esourceLanguage\x12'\n" +
	"\x0ftarget_language\x18\x02 \x01(\tR\x0etargetLanguage\x12\x1d\n" +
	"\n" +
	"enable_tts\x18\x03 \x01(\bR\tenableTts\x12\x1f\n" +
	"\vsample_rate\x18\x04 \x01(\x05R\n" +
	"sampleRateB\t\n" +
	"\apayload\"\xc3\x01\n" +
	"\rMediaResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12'\n" +
	"\x0frecognized_text\x18\x02 \x01(\tR\x0erecognizedText\x12'\n" +
	"\x0ftranslated_text\x18\x03 \x01(\tR\x0etranslatedText\x12\x19\n" +
	"\bis_final\x18\x04 \x01(\bR\aisFinal\x12&\n" +
	"\x0ftts_audio_chunk\x18\x05 \x01(\fR\rttsAudioChunk\"\xc5\x01\n" +
	"\vVideoConfig\x12\x1f\n" +
	"\veffect_type\x18\x01 \x01(\tR\n" +
	"effectType\x12'\n" +
	"\x0finference_width\x18\x02 \x01(\rR\x0einferenceWidth\x12)\n" +
	"\x10inference_height\x18\x03 \x01(\rR\x0finferenceHeight\x12#\n" +
	"\rinference_fps\x18\x04 \x01(\rR\finferenceFps\x12\x1c\n" +
	"\tthreshold\x18\x05 \x01(\x02R\tthreshold\"\xd7\x01\n" +
	"\n" +
	"VideoFrame\x12\x19\n" +
	"\bframe_id\x18\x01 \x01(\x03R\aframeId\x12#\n" +
	"\rrtp_timestamp\x18\x02 \x01(\x03R\frtpTimestamp\x12%\n" +
	"\x0eoriginal_width\x18\x03 \x01(\x05R\roriginalWidth\x12'\n" +
	"\x0foriginal_height\x18\x04 \x01(\x05R\x0eoriginalHeight\x12\x1a\n" +
	"\bencoding\x18\x05 \x01(\tR\bencoding\x12\x1d\n" +
	"\n" +
	"image_data\x18\x06 \x01(\fR\timageData\"\xcd\x01\n" +
	"\fVideoRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06is_eos\x18\x02 \x01(\bR\x05isEos\x120\n" +
	"\x06config\x18\x03 \x01(\v2\x16.mcf.ai.v1.VideoConfigH\x00R\x06config\x12-\n" +
	"\x05frame\x18\x04 \x01(\v2\x15.mcf.ai.v1.VideoFrameH\x00R\x05frame\x12\x1b\n" +
	"\tstream_id\x18\x05 \x01(\tR\bstreamIdB\t\n" +
	"\apayload\"\x86\x02\n" +
	"\tVideoMask\x12\x19\n" +
	"\bframe_id\x18\x01 \x01(\x03R\aframeId\x12#\n" +
	"\rrtp_timestamp\x18\x02 \x01(\x03R\frtpTimestamp\x12\x1d\n" +
	"\n" +
	"mask_width\x18\x03 \x01(\x05R\tmaskWidth\x12\x1f\n" +
	"\vmask_height\x18\x04 \x01(\x05R\n" +
	"maskHeight\x12\x1d\n" +
	"\n" +
	"rle_counts\x18\x05 \x03(\rR\trleCounts\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x06 \x01(\x02R\tlatencyMs\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\"\x90\x01\n" +
	"\rVideoResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12(\n" +
	"\x04mask\x18\x02 \x01(\v2\x14.mcf.ai.v1.VideoMaskR\x04mask\x12\x19\n" +
	"\bis_final\x18\x03 \x01(\bR\aisFinal\x12\x1b\n" +
	"\tstream_id\x18\x04 \x01(\tR\bstreamId2\xae\x01\n" +
	"\x12TranslationService\x12K\n" +
	"\x12ProcessMediaStream\x12\x17.mcf.ai.v1.MediaRequest\x1a\x18.mcf.ai.v1.MediaResponse(\x010\x01\x12K\n" +
	"\x12ProcessVideoStream\x12\x17.mcf.ai.v1.VideoRequest\x1a\x18.mcf.ai.v1.VideoResponse(\x010\x01B*Z(mcf/services/logic/internal/pb/api/protob\x06proto3"

var (
	file_ai_service_proto_rawDescOnce sync.Once
	file_ai_service_proto_rawDescData []byte
)

func file_ai_service_proto_rawDescGZIP() []byte {
	file_ai_service_proto_rawDescOnce.Do(func() {
		file_ai_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_service_proto_rawDesc), len(file_ai_service_proto_rawDesc)))
	})
	return file_ai_service_proto_rawDescData
}

var file_ai_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_ai_service_proto_goTypes = []any{
	(*MediaRequest)(nil),        // 0: mcf.ai.v1.MediaRequest
	(*MediaResponse)(nil),       // 1: mcf.ai.v1.MediaResponse
	(*VideoConfig)(nil),         // 2: mcf.ai.v1.VideoConfig
	(*VideoFrame)(nil),          // 3: mcf.ai.v1.VideoFrame
	(*VideoRequest)(nil),        // 4: mcf.ai.v1.VideoRequest
	(*VideoMask)(nil),           // 5: mcf.ai.v1.VideoMask
	(*VideoResponse)(nil),       // 6: mcf.ai.v1.VideoResponse
	(*MediaRequest_Config)(nil), // 7: mcf.ai.v1.MediaRequest.Config
}
var file_ai_service_proto_depIdxs = []int32{
	7, // 0: mcf.ai.v1.MediaRequest.config:type_name -> mcf.ai.v1.MediaRequest.Config
	2, // 1: mcf.ai.v1.VideoRequest.config:type_name -> mcf.ai.v1.VideoConfig
	3, // 2: mcf.ai.v1.VideoRequest.frame:type_name -> mcf.ai.v1.VideoFrame
	5, // 3: mcf.ai.v1.VideoResponse.mask:type_name -> mcf.ai.v1.VideoMask
	0, // 4: mcf.ai.v1.TranslationService.ProcessMediaStream:input_type -> mcf.ai.v1.MediaRequest
	4, // 5: mcf.ai.v1.TranslationService.ProcessVideoStream:input_type -> mcf.ai.v1.VideoRequest
	1, // 6: mcf.ai.v1.TranslationService.ProcessMediaStream:output_type -> mcf.ai.v1.MediaResponse
	6, // 7: mcf.ai.v1.TranslationService.ProcessVideoStream:output_type -> mcf.ai.v1.VideoResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ai_service_proto_init() }
func file_ai_service_proto_init() {
	if File_ai_service_proto != nil {
		return
	}
	file_ai_service_proto_msgTypes[0].OneofWrappers = []any{
		(*MediaRequest_Config_)(nil),
		(*MediaRequest_AudioChunk)(nil),
	}
	file_ai_service_proto_msgTypes[4].OneofWrappers = []any{
		(*VideoRequest_Config)(nil),
		(*VideoRequest_Frame)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_service_proto_rawDesc), len(file_ai_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_service_proto_goTypes,
		DependencyIndexes: file_ai_service_proto_depIdxs,
		MessageInfos:      file_ai_service_proto_msgTypes,
	}.Build()
	File_ai_service_proto = out.File
	file_ai_service_proto_goTypes = nil
	file_ai_service_proto_depIdxs = nil
}
