// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: api/proto/ai_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TranslationService_ProcessMediaStream_FullMethodName = "/mcf.ai.v1.TranslationService/ProcessMediaStream"
)

// TranslationServiceClient is the client API for TranslationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ---------------------------------------------------------
// SERVICE DEFINITION
// ---------------------------------------------------------
type TranslationServiceClient interface {
	ProcessMediaStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MediaRequest, MediaResponse], error)
}

type translationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTranslationServiceClient(cc grpc.ClientConnInterface) TranslationServiceClient {
	return &translationServiceClient{cc}
}

func (c *translationServiceClient) ProcessMediaStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MediaRequest, MediaResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TranslationService_ServiceDesc.Streams[0], TranslationService_ProcessMediaStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MediaRequest, MediaResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TranslationService_ProcessMediaStreamClient = grpc.BidiStreamingClient[MediaRequest, MediaResponse]

// TranslationServiceServer is the server API for TranslationService service.
// All implementations must embed UnimplementedTranslationServiceServer
// for forward compatibility.
//
// ---------------------------------------------------------
// SERVICE DEFINITION
// ---------------------------------------------------------
type TranslationServiceServer interface {
	ProcessMediaStream(grpc.BidiStreamingServer[MediaRequest, MediaResponse]) error
	mustEmbedUnimplementedTranslationServiceServer()
}

// UnimplementedTranslationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTranslationServiceServer struct{}

func (UnimplementedTranslationServiceServer) ProcessMediaStream(grpc.BidiStreamingServer[MediaRequest, MediaResponse]) error {
	return status.Error(codes.Unimplemented, "method ProcessMediaStream not implemented")
}
func (UnimplementedTranslationServiceServer) mustEmbedUnimplementedTranslationServiceServer() {}
func (UnimplementedTranslationServiceServer) testEmbeddedByValue()                            {}

// UnsafeTranslationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TranslationServiceServer will
// result in compilation errors.
type UnsafeTranslationServiceServer interface {
	mustEmbedUnimplementedTranslationServiceServer()
}

func RegisterTranslationServiceServer(s grpc.ServiceRegistrar, srv TranslationServiceServer) {
	// If the following call panics, it indicates UnimplementedTranslationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TranslationService_ServiceDesc, srv)
}

func _TranslationService_ProcessMediaStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TranslationServiceServer).ProcessMediaStream(&grpc.GenericServerStream[MediaRequest, MediaResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TranslationService_ProcessMediaStreamServer = grpc.BidiStreamingServer[MediaRequest, MediaResponse]

// TranslationService_ServiceDesc is the grpc.ServiceDesc for TranslationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TranslationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mcf.ai.v1.TranslationService",
	HandlerType: (*TranslationServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessMediaStream",
			Handler:       _TranslationService_ProcessMediaStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/ai_service.proto",
}
