// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: api/proto/ai_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ---------------------------------------------------------
// REQUEST DEFINITION (Go -> Python)
// ---------------------------------------------------------
type MediaRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// using 'oneof' to classify: one request can only be either config or media chunk.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*MediaRequest_Config_
	//	*MediaRequest_AudioChunk
	Payload        isMediaRequest_Payload `protobuf_oneof:"payload"`
	SequenceNumber int64                  `protobuf:"varint,4,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"` // to maintain the order of requests
	IsEos          bool                   `protobuf:"varint,5,opt,name=is_eos,json=isEos,proto3" json:"is_eos,omitempty"`                            // end of stream indicator
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MediaRequest) Reset() {
	*x = MediaRequest{}
	mi := &file_api_proto_ai_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaRequest) ProtoMessage() {}

func (x *MediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ai_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaRequest.ProtoReflect.Descriptor instead.
func (*MediaRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_ai_service_proto_rawDescGZIP(), []int{0}
}

func (x *MediaRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MediaRequest) GetPayload() isMediaRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MediaRequest) GetConfig() *MediaRequest_Config {
	if x != nil {
		if x, ok := x.Payload.(*MediaRequest_Config_); ok {
			return x.Config
		}
	}
	return nil
}

func (x *MediaRequest) GetAudioChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*MediaRequest_AudioChunk); ok {
			return x.AudioChunk
		}
	}
	return nil
}

func (x *MediaRequest) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *MediaRequest) GetIsEos() bool {
	if x != nil {
		return x.IsEos
	}
	return false
}

type isMediaRequest_Payload interface {
	isMediaRequest_Payload()
}

type MediaRequest_Config_ struct {
	Config *MediaRequest_Config `protobuf:"bytes,2,opt,name=config,proto3,oneof"` // setup
}

type MediaRequest_AudioChunk struct {
	AudioChunk []byte `protobuf:"bytes,3,opt,name=audio_chunk,json=audioChunk,proto3,oneof"` // pcm audio data
}

func (*MediaRequest_Config_) isMediaRequest_Payload() {}

func (*MediaRequest_AudioChunk) isMediaRequest_Payload() {}

// ---------------------------------------------------------
// RESPONSE DEFINITION (Python -> Go)
// ---------------------------------------------------------
type MediaResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// text response (serve HTTPGW export subtitles)
	RecognizedText string `protobuf:"bytes,2,opt,name=recognized_text,json=recognizedText,proto3" json:"recognized_text,omitempty"` // ASR
	TranslatedText string `protobuf:"bytes,3,opt,name=translated_text,json=translatedText,proto3" json:"translated_text,omitempty"` // MT
	// flag to indicate if this is the final response for the current session
	IsFinal bool `protobuf:"varint,4,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	// audio data (RTPGW audio response)
	TtsAudioChunk []byte `protobuf:"bytes,5,opt,name=tts_audio_chunk,json=ttsAudioChunk,proto3" json:"tts_audio_chunk,omitempty"` // pcm audio data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaResponse) Reset() {
	*x = MediaResponse{}
	mi := &file_api_proto_ai_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaResponse) ProtoMessage() {}

func (x *MediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ai_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaResponse.ProtoReflect.Descriptor instead.
func (*MediaResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_ai_service_proto_rawDescGZIP(), []int{1}
}

func (x *MediaResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MediaResponse) GetRecognizedText() string {
	if x != nil {
		return x.RecognizedText
	}
	return ""
}

func (x *MediaResponse) GetTranslatedText() string {
	if x != nil {
		return x.TranslatedText
	}
	return ""
}

func (x *MediaResponse) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *MediaResponse) GetTtsAudioChunk() []byte {
	if x != nil {
		return x.TtsAudioChunk
	}
	return nil
}

type MediaRequest_Config struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceLanguage string                 `protobuf:"bytes,1,opt,name=source_language,json=sourceLanguage,proto3" json:"source_language,omitempty"`
	TargetLanguage string                 `protobuf:"bytes,2,opt,name=target_language,json=targetLanguage,proto3" json:"target_language,omitempty"`
	EnableTts      bool                   `protobuf:"varint,3,opt,name=enable_tts,json=enableTts,proto3" json:"enable_tts,omitempty"`
	SampleRate     int32                  `protobuf:"varint,4,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MediaRequest_Config) Reset() {
	*x = MediaRequest_Config{}
	mi := &file_api_proto_ai_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaRequest_Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaRequest_Config) ProtoMessage() {}

func (x *MediaRequest_Config) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ai_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaRequest_Config.ProtoReflect.Descriptor instead.
func (*MediaRequest_Config) Descriptor() ([]byte, []int) {
	return file_api_proto_ai_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MediaRequest_Config) GetSourceLanguage() string {
	if x != nil {
		return x.SourceLanguage
	}
	return ""
}

func (x *MediaRequest_Config) GetTargetLanguage() string {
	if x != nil {
		return x.TargetLanguage
	}
	return ""
}

func (x *MediaRequest_Config) GetEnableTts() bool {
	if x != nil {
		return x.EnableTts
	}
	return false
}

func (x *MediaRequest_Config) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

var File_api_proto_ai_service_proto protoreflect.FileDescriptor

const file_api_proto_ai_service_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/ai_service.proto\x12\tmcf.ai.v1\"\xf2\x02\n" +
	"\fMediaRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x128\n" +
	"\x06config\x18\x02 \x01(\v2\x1e.mcf.ai.v1.MediaRequest.ConfigH\x00R\x06config\x12!\n" +
	"\vaudio_chunk\x18\x03 \x01(\fH\x00R\n" +
	"audioChunk\x12'\n" +
	"\x0fsequence_number\x18\x04 \x01(\x03R\x0esequenceNumber\x12\x15\n" +
	"\x06is_eos\x18\x05 \x01(\bR\x05isEos\x1a\x9a\x01\n" +
	"\x06Config\x12'\n" +
	"\x0fsource_language\x18\x01 \x01(\tR\x0esourceLanguage\x12'\n" +
	"\x0ftarget_language\x18\x02 \x01(\tR\x0etargetLanguage\x12\x1d\n" +
	"\n" +
	"enable_tts\x18\x03 \x01(\bR\tenableTts\x12\x1f\n" +
	"\vsample_rate\x18\x04 \x01(\x05R\n" +
	"sampleRateB\t\n" +
	"\apayload\"\xc3\x01\n" +
	"\rMediaResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12'\n" +
	"\x0frecognized_text\x18\x02 \x01(\tR\x0erecognizedText\x12'\n" +
	"\x0ftranslated_text\x18\x03 \x01(\tR\x0etranslatedText\x12\x19\n" +
	"\bis_final\x18\x04 \x01(\bR\aisFinal\x12&\n" +
	"\x0ftts_audio_chunk\x18\x05 \x01(\fR\rttsAudioChunk2a\n" +
	"\x12TranslationService\x12K\n" +
	"\x12ProcessMediaStream\x12\x17.mcf.ai.v1.MediaRequest\x1a\x18.mcf.ai.v1.MediaResponse(\x010\x01B Z\x1emcf/services/logic/internal/pbb\x06proto3"

var (
	file_api_proto_ai_service_proto_rawDescOnce sync.Once
	file_api_proto_ai_service_proto_rawDescData []byte
)

func file_api_proto_ai_service_proto_rawDescGZIP() []byte {
	file_api_proto_ai_service_proto_rawDescOnce.Do(func() {
		file_api_proto_ai_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_ai_service_proto_rawDesc), len(file_api_proto_ai_service_proto_rawDesc)))
	})
	return file_api_proto_ai_service_proto_rawDescData
}

var file_api_proto_ai_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_ai_service_proto_goTypes = []any{
	(*MediaRequest)(nil),        // 0: mcf.ai.v1.MediaRequest
	(*MediaResponse)(nil),       // 1: mcf.ai.v1.MediaResponse
	(*MediaRequest_Config)(nil), // 2: mcf.ai.v1.MediaRequest.Config
}
var file_api_proto_ai_service_proto_depIdxs = []int32{
	2, // 0: mcf.ai.v1.MediaRequest.config:type_name -> mcf.ai.v1.MediaRequest.Config
	0, // 1: mcf.ai.v1.TranslationService.ProcessMediaStream:input_type -> mcf.ai.v1.MediaRequest
	1, // 2: mcf.ai.v1.TranslationService.ProcessMediaStream:output_type -> mcf.ai.v1.MediaResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_ai_service_proto_init() }
func file_api_proto_ai_service_proto_init() {
	if File_api_proto_ai_service_proto != nil {
		return
	}
	file_api_proto_ai_service_proto_msgTypes[0].OneofWrappers = []any{
		(*MediaRequest_Config_)(nil),
		(*MediaRequest_AudioChunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_ai_service_proto_rawDesc), len(file_api_proto_ai_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_ai_service_proto_goTypes,
		DependencyIndexes: file_api_proto_ai_service_proto_depIdxs,
		MessageInfos:      file_api_proto_ai_service_proto_msgTypes,
	}.Build()
	File_api_proto_ai_service_proto = out.File
	file_api_proto_ai_service_proto_goTypes = nil
	file_api_proto_ai_service_proto_depIdxs = nil
}
