// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: video_ingest.proto

// video_ingest.proto
//
// v3.2 (see rtpgw_design_v3.md section 37). MF no longer decodes H264 at
// all -- decode moved entirely into RTPGW (embedded C++ decoder via cgo,
// see services/logic/internal/video/cdecoder/). MF's role is now strictly
// "forward RTP + compositor": it forwards every RTP packet to RTPGW
// unchanged, and RTPGW decodes ONCE and fans the result out two ways:
//   1. every decoded frame, raw (DecodedFrame), streamed straight back to
//      MF over THIS SAME connection, for MF's compositor to consume;
//   2. a FPS-sampled + JPEG-encoded subset, forwarded on to the AI Engine
//      over the separate RTPGW <-> AI Engine gRPC stream (ai_service.proto,
//      unchanged from v3.1).
// The AI Engine still pushes mask results directly to MF over HTTP
// (unchanged from v3.1) -- RTPGW is never in the mask's return path.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VideoIngestService_Transport_FullMethodName = "/mcf.video.v1.VideoIngestService/Transport"
)

// VideoIngestServiceClient is the client API for VideoIngestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ---------------------------------------------------------
// SERVICE DEFINITION
// ---------------------------------------------------------
type VideoIngestServiceClient interface {
	// MF -> RTPGW: RtpFrame (open/packet/eos), standard RTP fields only.
	// RTPGW -> MF: IngestResponse, either a control IngestEvent or an actual
	// DecodedFrame -- see the two are now interleaved on the SAME stream, so
	// MF's reader thread must switch on IngestResponse.payload.
	Transport(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RtpFrame, IngestResponse], error)
}

type videoIngestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoIngestServiceClient(cc grpc.ClientConnInterface) VideoIngestServiceClient {
	return &videoIngestServiceClient{cc}
}

func (c *videoIngestServiceClient) Transport(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RtpFrame, IngestResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VideoIngestService_ServiceDesc.Streams[0], VideoIngestService_Transport_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RtpFrame, IngestResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VideoIngestService_TransportClient = grpc.BidiStreamingClient[RtpFrame, IngestResponse]

// VideoIngestServiceServer is the server API for VideoIngestService service.
// All implementations must embed UnimplementedVideoIngestServiceServer
// for forward compatibility.
//
// ---------------------------------------------------------
// SERVICE DEFINITION
// ---------------------------------------------------------
type VideoIngestServiceServer interface {
	// MF -> RTPGW: RtpFrame (open/packet/eos), standard RTP fields only.
	// RTPGW -> MF: IngestResponse, either a control IngestEvent or an actual
	// DecodedFrame -- see the two are now interleaved on the SAME stream, so
	// MF's reader thread must switch on IngestResponse.payload.
	Transport(grpc.BidiStreamingServer[RtpFrame, IngestResponse]) error
	mustEmbedUnimplementedVideoIngestServiceServer()
}

// UnimplementedVideoIngestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVideoIngestServiceServer struct{}

func (UnimplementedVideoIngestServiceServer) Transport(grpc.BidiStreamingServer[RtpFrame, IngestResponse]) error {
	return status.Error(codes.Unimplemented, "method Transport not implemented")
}
func (UnimplementedVideoIngestServiceServer) mustEmbedUnimplementedVideoIngestServiceServer() {}
func (UnimplementedVideoIngestServiceServer) testEmbeddedByValue()                            {}

// UnsafeVideoIngestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoIngestServiceServer will
// result in compilation errors.
type UnsafeVideoIngestServiceServer interface {
	mustEmbedUnimplementedVideoIngestServiceServer()
}

func RegisterVideoIngestServiceServer(s grpc.ServiceRegistrar, srv VideoIngestServiceServer) {
	// If the following call panics, it indicates UnimplementedVideoIngestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VideoIngestService_ServiceDesc, srv)
}

func _VideoIngestService_Transport_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VideoIngestServiceServer).Transport(&grpc.GenericServerStream[RtpFrame, IngestResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VideoIngestService_TransportServer = grpc.BidiStreamingServer[RtpFrame, IngestResponse]

// VideoIngestService_ServiceDesc is the grpc.ServiceDesc for VideoIngestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoIngestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mcf.video.v1.VideoIngestService",
	HandlerType: (*VideoIngestServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Transport",
			Handler:       _VideoIngestService_Transport_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "video_ingest.proto",
}
