// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: video_ingest.proto

// video_ingest.proto
//
// v3.2 (see rtpgw_design_v3.md section 37). MF no longer decodes H264 at
// all -- decode moved entirely into RTPGW (embedded C++ decoder via cgo,
// see services/logic/internal/video/cdecoder/). MF's role is now strictly
// "forward RTP + compositor": it forwards every RTP packet to RTPGW
// unchanged, and RTPGW decodes ONCE and fans the result out two ways:
//   1. every decoded frame, raw (DecodedFrame), streamed straight back to
//      MF over THIS SAME connection, for MF's compositor to consume;
//   2. a FPS-sampled + JPEG-encoded subset, forwarded on to the AI Engine
//      over the separate RTPGW <-> AI Engine gRPC stream (ai_service.proto,
//      unchanged from v3.1).
// The AI Engine still pushes mask results directly to MF over HTTP
// (unchanged from v3.1) -- RTPGW is never in the mask's return path.

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RtpOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StreamId      string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`           // e.g. "call-001:taccess:video"
	Leg           string                 `protobuf:"bytes,3,opt,name=leg,proto3" json:"leg,omitempty"`                                     // "tcore" | "taccess"
	Codec         string                 `protobuf:"bytes,4,opt,name=codec,proto3" json:"codec,omitempty"`                                 // "H264"
	ClockRate     uint32                 `protobuf:"varint,5,opt,name=clock_rate,json=clockRate,proto3" json:"clock_rate,omitempty"`       // 90000 for H264
	EffectType    string                 `protobuf:"bytes,6,opt,name=effect_type,json=effectType,proto3" json:"effect_type,omitempty"`     // "bg_replace" | "bg_blur" | "bg_remove"
	TargetWidth   int32                  `protobuf:"varint,7,opt,name=target_width,json=targetWidth,proto3" json:"target_width,omitempty"` // AI inference resize target (JPEG leg)
	TargetHeight  int32                  `protobuf:"varint,8,opt,name=target_height,json=targetHeight,proto3" json:"target_height,omitempty"`
	TargetFps     int32                  `protobuf:"varint,9,opt,name=target_fps,json=targetFps,proto3" json:"target_fps,omitempty"`               // AI inference sampling FPS (JPEG leg)
	MfCallbackUrl string                 `protobuf:"bytes,10,opt,name=mf_callback_url,json=mfCallbackUrl,proto3" json:"mf_callback_url,omitempty"` // where the AI Engine pushes mask results
	// NEW in v3.2: the resolution MF's own VideoWriter/compositor is
	// configured for (its --width/--height CLI flags). RTPGW's embedded
	// decoder MUST decode+return raw frames at exactly this resolution, or
	// MF's compose()/writer_.write() will fail/corrupt -- previously this
	// was two independently-configured values (MF's --width/--height vs
	// RTPGW's VIDEO_FRAME_WIDTH/HEIGHT env var) that had to be kept in sync
	// by hand; carrying it in RtpOpen removes that footgun (see
	// rtpgw_design_v3.md section 35.6 for the class of bug this caused
	// before, and section 37 for this fix).
	DecodeWidth   int32 `protobuf:"varint,11,opt,name=decode_width,json=decodeWidth,proto3" json:"decode_width,omitempty"`
	DecodeHeight  int32 `protobuf:"varint,12,opt,name=decode_height,json=decodeHeight,proto3" json:"decode_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RtpOpen) Reset() {
	*x = RtpOpen{}
	mi := &file_video_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RtpOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtpOpen) ProtoMessage() {}

func (x *RtpOpen) ProtoReflect() protoreflect.Message {
	mi := &file_video_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtpOpen.ProtoReflect.Descriptor instead.
func (*RtpOpen) Descriptor() ([]byte, []int) {
	return file_video_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *RtpOpen) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RtpOpen) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *RtpOpen) GetLeg() string {
	if x != nil {
		return x.Leg
	}
	return ""
}

func (x *RtpOpen) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *RtpOpen) GetClockRate() uint32 {
	if x != nil {
		return x.ClockRate
	}
	return 0
}

func (x *RtpOpen) GetEffectType() string {
	if x != nil {
		return x.EffectType
	}
	return ""
}

func (x *RtpOpen) GetTargetWidth() int32 {
	if x != nil {
		return x.TargetWidth
	}
	return 0
}

func (x *RtpOpen) GetTargetHeight() int32 {
	if x != nil {
		return x.TargetHeight
	}
	return 0
}

func (x *RtpOpen) GetTargetFps() int32 {
	if x != nil {
		return x.TargetFps
	}
	return 0
}

func (x *RtpOpen) GetMfCallbackUrl() string {
	if x != nil {
		return x.MfCallbackUrl
	}
	return ""
}

func (x *RtpOpen) GetDecodeWidth() int32 {
	if x != nil {
		return x.DecodeWidth
	}
	return 0
}

func (x *RtpOpen) GetDecodeHeight() int32 {
	if x != nil {
		return x.DecodeHeight
	}
	return 0
}

type RtpPacket struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber uint32                 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Timestamp      uint32                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Ssrc           uint32                 `protobuf:"varint,3,opt,name=ssrc,proto3" json:"ssrc,omitempty"`
	Marker         bool                   `protobuf:"varint,4,opt,name=marker,proto3" json:"marker,omitempty"`
	PayloadType    uint32                 `protobuf:"varint,5,opt,name=payload_type,json=payloadType,proto3" json:"payload_type,omitempty"`
	Payload        []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RtpPacket) Reset() {
	*x = RtpPacket{}
	mi := &file_video_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RtpPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtpPacket) ProtoMessage() {}

func (x *RtpPacket) ProtoReflect() protoreflect.Message {
	mi := &file_video_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtpPacket.ProtoReflect.Descriptor instead.
func (*RtpPacket) Descriptor() ([]byte, []int) {
	return file_video_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *RtpPacket) GetSequenceNumber() uint32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *RtpPacket) GetTimestamp() uint32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RtpPacket) GetSsrc() uint32 {
	if x != nil {
		return x.Ssrc
	}
	return 0
}

func (x *RtpPacket) GetMarker() bool {
	if x != nil {
		return x.Marker
	}
	return false
}

func (x *RtpPacket) GetPayloadType() uint32 {
	if x != nil {
		return x.PayloadType
	}
	return 0
}

func (x *RtpPacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type RtpFrame struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StreamId  string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	IsEos     bool                   `protobuf:"varint,3,opt,name=is_eos,json=isEos,proto3" json:"is_eos,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RtpFrame_Open
	//	*RtpFrame_Packet
	Payload       isRtpFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RtpFrame) Reset() {
	*x = RtpFrame{}
	mi := &file_video_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RtpFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtpFrame) ProtoMessage() {}

func (x *RtpFrame) ProtoReflect() protoreflect.Message {
	mi := &file_video_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtpFrame.ProtoReflect.Descriptor instead.
func (*RtpFrame) Descriptor() ([]byte, []int) {
	return file_video_ingest_proto_rawDescGZIP(), []int{2}
}

func (x *RtpFrame) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RtpFrame) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *RtpFrame) GetIsEos() bool {
	if x != nil {
		return x.IsEos
	}
	return false
}

func (x *RtpFrame) GetPayload() isRtpFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RtpFrame) GetOpen() *RtpOpen {
	if x != nil {
		if x, ok := x.Payload.(*RtpFrame_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *RtpFrame) GetPacket() *RtpPacket {
	if x != nil {
		if x, ok := x.Payload.(*RtpFrame_Packet); ok {
			return x.Packet
		}
	}
	return nil
}

type isRtpFrame_Payload interface {
	isRtpFrame_Payload()
}

type RtpFrame_Open struct {
	Open *RtpOpen `protobuf:"bytes,4,opt,name=open,proto3,oneof"`
}

type RtpFrame_Packet struct {
	Packet *RtpPacket `protobuf:"bytes,5,opt,name=packet,proto3,oneof"`
}

func (*RtpFrame_Open) isRtpFrame_Payload() {}

func (*RtpFrame_Packet) isRtpFrame_Payload() {}

// One fully decoded frame, raw pixels, at MF's decode_width x decode_height
// (see RtpOpen above). encoding is always "bgr24" (OpenCV's native channel
// order, matching what MF's compose() already expects -- zero conversion
// needed on MF's side when building a cv::Mat from frame_data). NOT
// FPS-sampled: every frame RTPGW decodes is sent here, since MF's
// compositor needs continuity to produce a normal-looking output video
// (only the separate RTPGW -> AI Engine leg is FPS-sampled).
type DecodedFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameId       int64                  `protobuf:"varint,1,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"` // RTPGW's own counter, independent of AI-leg frame_id
	RtpTimestamp  uint32                 `protobuf:"varint,2,opt,name=rtp_timestamp,json=rtpTimestamp,proto3" json:"rtp_timestamp,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Encoding      string                 `protobuf:"bytes,5,opt,name=encoding,proto3" json:"encoding,omitempty"` // "bgr24"
	FrameData     []byte                 `protobuf:"bytes,6,opt,name=frame_data,json=frameData,proto3" json:"frame_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodedFrame) Reset() {
	*x = DecodedFrame{}
	mi := &file_video_ingest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodedFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodedFrame) ProtoMessage() {}

func (x *DecodedFrame) ProtoReflect() protoreflect.Message {
	mi := &file_video_ingest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodedFrame.ProtoReflect.Descriptor instead.
func (*DecodedFrame) Descriptor() ([]byte, []int) {
	return file_video_ingest_proto_rawDescGZIP(), []int{3}
}

func (x *DecodedFrame) GetFrameId() int64 {
	if x != nil {
		return x.FrameId
	}
	return 0
}

func (x *DecodedFrame) GetRtpTimestamp() uint32 {
	if x != nil {
		return x.RtpTimestamp
	}
	return 0
}

func (x *DecodedFrame) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *DecodedFrame) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *DecodedFrame) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

func (x *DecodedFrame) GetFrameData() []byte {
	if x != nil {
		return x.FrameData
	}
	return nil
}

type IngestEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StreamId        string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "opened" | "ack" | "warn" | "error" | "closed"
	Message         string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	PacketsReceived uint64                 `protobuf:"varint,5,opt,name=packets_received,json=packetsReceived,proto3" json:"packets_received,omitempty"`
	FramesDecoded   uint64                 `protobuf:"varint,6,opt,name=frames_decoded,json=framesDecoded,proto3" json:"frames_decoded,omitempty"`
	FramesDropped   uint64                 `protobuf:"varint,7,opt,name=frames_dropped,json=framesDropped,proto3" json:"frames_dropped,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IngestEvent) Reset() {
	*x = IngestEvent{}
	mi := &file_video_ingest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEvent) ProtoMessage() {}

func (x *IngestEvent) ProtoReflect() protoreflect.Message {
	mi := &file_video_ingest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEvent.ProtoReflect.Descriptor instead.
func (*IngestEvent) Descriptor() ([]byte, []int) {
	return file_video_ingest_proto_rawDescGZIP(), []int{4}
}

func (x *IngestEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *IngestEvent) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *IngestEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *IngestEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *IngestEvent) GetPacketsReceived() uint64 {
	if x != nil {
		return x.PacketsReceived
	}
	return 0
}

func (x *IngestEvent) GetFramesDecoded() uint64 {
	if x != nil {
		return x.FramesDecoded
	}
	return 0
}

func (x *IngestEvent) GetFramesDropped() uint64 {
	if x != nil {
		return x.FramesDropped
	}
	return 0
}

type IngestResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StreamId  string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*IngestResponse_Event
	//	*IngestResponse_Frame
	Payload       isIngestResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_video_ingest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_ingest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_video_ingest_proto_rawDescGZIP(), []int{5}
}

func (x *IngestResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *IngestResponse) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *IngestResponse) GetPayload() isIngestResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *IngestResponse) GetEvent() *IngestEvent {
	if x != nil {
		if x, ok := x.Payload.(*IngestResponse_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *IngestResponse) GetFrame() *DecodedFrame {
	if x != nil {
		if x, ok := x.Payload.(*IngestResponse_Frame); ok {
			return x.Frame
		}
	}
	return nil
}

type isIngestResponse_Payload interface {
	isIngestResponse_Payload()
}

type IngestResponse_Event struct {
	Event *IngestEvent `protobuf:"bytes,3,opt,name=event,proto3,oneof"`
}

type IngestResponse_Frame struct {
	Frame *DecodedFrame `protobuf:"bytes,4,opt,name=frame,proto3,oneof"`
}

func (*IngestResponse_Event) isIngestResponse_Payload() {}

func (*IngestResponse_Frame) isIngestResponse_Payload() {}

var File_video_ingest_proto protoreflect.FileDescriptor

const file_video_ingest_proto_rawDesc = "" +
	"\n" +
	"\x12video_ingest.proto\x12\fmcf.video.v1\"\x84\x03\n" +
	"\aRtpOpen\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x12\x10\n" +
	"\x03leg\x18\x03 \x01(\tR\x03leg\x12\x14\n" +
	"\x05codec\x18\x04 \x01(\tR\x05codec\x12\x1d\n" +
	"\n" +
	"clock_rate\x18\x05 \x01(\rR\tclockRate\x12\x1f\n" +
	"\veffect_type\x18\x06 \x01(\tR\n" +
	"effectType\x12!\n" +
	"\ftarget_width\x18\a \x01(\x05R\vtargetWidth\x12#\n" +
	"\rtarget_height\x18\b \x01(\x05R\ftargetHeight\x12\x1d\n" +
	"\n" +
	"target_fps\x18\t \x01(\x05R\ttargetFps\x12&\n" +
	"\x0fmf_callback_url\x18\n" +
	" \x01(\tR\rmfCallbackUrl\x12!\n" +
	"\fdecode_width\x18\v \x01(\x05R\vdecodeWidth\x12#\n" +
	"\rdecode_height\x18\f \x01(\x05R\fdecodeHeight\"\xbb\x01\n" +
	"\tRtpPacket\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\rR\x0esequenceNumber\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\rR\ttimestamp\x12\x12\n" +
	"\x04ssrc\x18\x03 \x01(\rR\x04ssrc\x12\x16\n" +
	"\x06marker\x18\x04 \x01(\bR\x06marker\x12!\n" +
	"\fpayload_type\x18\x05 \x01(\rR\vpayloadType\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\"\xc8\x01\n" +
	"\bRtpFrame\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x12\x15\n" +
	"\x06is_eos\x18\x03 \x01(\bR\x05isEos\x12+\n" +
	"\x04open\x18\x04 \x01(\v2\x15.mcf.video.v1.RtpOpenH\x00R\x04open\x121\n" +
	"\x06packet\x18\x05 \x01(\v2\x17.mcf.video.v1.RtpPacketH\x00R\x06packetB\t\n" +
	"\apayload\"\xb7\x01\n" +
	"\fDecodedFrame\x12\x19\n" +
	"\bframe_id\x18\x01 \x01(\x03R\aframeId\x12#\n" +
	"\rrtp_timestamp\x18\x02 \x01(\rR\frtpTimestamp\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12\x1a\n" +
	"\bencoding\x18\x05 \x01(\tR\bencoding\x12\x1d\n" +
	"\n" +
	"frame_data\x18\x06 \x01(\fR\tframeData\"\xf4\x01\n" +
	"\vIngestEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12)\n" +
	"\x10packets_received\x18\x05 \x01(\x04R\x0fpacketsReceived\x12%\n" +
	"\x0eframes_decoded\x18\x06 \x01(\x04R\rframesDecoded\x12%\n" +
	"\x0eframes_dropped\x18\a \x01(\x04R\rframesDropped\"\xbe\x01\n" +
	"\x0eIngestResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x121\n" +
	"\x05event\x18\x03 \x01(\v2\x19.mcf.video.v1.IngestEventH\x00R\x05event\x122\n" +
	"\x05frame\x18\x04 \x01(\v2\x1a.mcf.video.v1.DecodedFrameH\x00R\x05frameB\t\n" +
	"\apayload2[\n" +
	"\x12VideoIngestService\x12E\n" +
	"\tTransport\x12\x16.mcf.video.v1.RtpFrame\x1a\x1c.mcf.video.v1.IngestResponse(\x010\x01B*Z(mcf/services/logic/internal/pb/api/protob\x06proto3"

var (
	file_video_ingest_proto_rawDescOnce sync.Once
	file_video_ingest_proto_rawDescData []byte
)

func file_video_ingest_proto_rawDescGZIP() []byte {
	file_video_ingest_proto_rawDescOnce.Do(func() {
		file_video_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_video_ingest_proto_rawDesc), len(file_video_ingest_proto_rawDesc)))
	})
	return file_video_ingest_proto_rawDescData
}

var file_video_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_video_ingest_proto_goTypes = []any{
	(*RtpOpen)(nil),        // 0: mcf.video.v1.RtpOpen
	(*RtpPacket)(nil),      // 1: mcf.video.v1.RtpPacket
	(*RtpFrame)(nil),       // 2: mcf.video.v1.RtpFrame
	(*DecodedFrame)(nil),   // 3: mcf.video.v1.DecodedFrame
	(*IngestEvent)(nil),    // 4: mcf.video.v1.IngestEvent
	(*IngestResponse)(nil), // 5: mcf.video.v1.IngestResponse
}
var file_video_ingest_proto_depIdxs = []int32{
	0, // 0: mcf.video.v1.RtpFrame.open:type_name -> mcf.video.v1.RtpOpen
	1, // 1: mcf.video.v1.RtpFrame.packet:type_name -> mcf.video.v1.RtpPacket
	4, // 2: mcf.video.v1.IngestResponse.event:type_name -> mcf.video.v1.IngestEvent
	3, // 3: mcf.video.v1.IngestResponse.frame:type_name -> mcf.video.v1.DecodedFrame
	2, // 4: mcf.video.v1.VideoIngestService.Transport:input_type -> mcf.video.v1.RtpFrame
	5, // 5: mcf.video.v1.VideoIngestService.Transport:output_type -> mcf.video.v1.IngestResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_video_ingest_proto_init() }
func file_video_ingest_proto_init() {
	if File_video_ingest_proto != nil {
		return
	}
	file_video_ingest_proto_msgTypes[2].OneofWrappers = []any{
		(*RtpFrame_Open)(nil),
		(*RtpFrame_Packet)(nil),
	}
	file_video_ingest_proto_msgTypes[5].OneofWrappers = []any{
		(*IngestResponse_Event)(nil),
		(*IngestResponse_Frame)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_video_ingest_proto_rawDesc), len(file_video_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_video_ingest_proto_goTypes,
		DependencyIndexes: file_video_ingest_proto_depIdxs,
		MessageInfos:      file_video_ingest_proto_msgTypes,
	}.Build()
	File_video_ingest_proto = out.File
	file_video_ingest_proto_goTypes = nil
	file_video_ingest_proto_depIdxs = nil
}
